### ISSUE TITLE
Work on shopping_lists functionality 

### ISSUE THREAD

**Issue by rhyusarmiento** [Benjibuns/app-in-a-day#23]
**Please describe your feature.**
This Feature will enable the functionality behind the shopping_lists function

**Describe the solution you'd like**
to provide the data for the page

**Comment by Benjibuns** [comment]
what functionality is this doing in shopping_lists? is this adding a new list? or creating database? adding items?

**Comment by rhyusarmiento** [comment]
Sorry! let me explain. So basically what the functionality is to return the shopping lists so the front end can use it

**Comment by Benjibuns** [comment]
Ok.  Sounds like you are going to connect the database up to the front end?  You will send a list of shopping_lists to the front end?  How are you creating the lists?  Did you already have the ability to create lists?
